default:
  interruptible: true
  image: registry.gitlab.com/kage-yami/dockerfile/rust:1.49.0-main
  retry:
    max: 2
    when:
      - runner_system_failure

stages:
  - test
  - check
  - publish

cache:
  key: $CI_COMMIT_REF_SLUG.$CI_JOB_NAME
  paths:
    - target

.test: &test
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success

.check: &check
  stage: check
  rules: &publish-rules
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never

.publish: &publish
  stage: publish
  rules: *publish-rules

test:
  <<: *test
  script:
    - cargo test

lint:
  <<: *test
  script:
    - cargo clippy &> >(tee lint.txt)
#    - test $(grep --count '^warning' lint.txt) -eq 0

coverage:
  <<: *test
  script:
    - cargo tarpaulin --verbose

format:
  <<: *test
  script:
    - cargo fmt -- --check

package:
  <<: *test
  script:
    - cargo package

version:
  <<: *check
  script:
    - cargo test --package dataweave --test version html_root_url -- --exact
    - version=$(grep -Eo '^version = "[^"]*"$' Cargo.toml  | sed -E 's|.+ = "([^"]+)"$|\1|')
    - test $version = $CI_COMMIT_TAG

publish:
  <<: *publish
  script:
    - cargo login $CRATES_IO_TOKEN
    - cargo publish

release:
  <<: *publish
  image: registry.gitlab.com/gitlab-org/release-cli:v0.5.0
  script:
    - echo "Creating release..."
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG"
