on:
  - push

jobs:
  aarch64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-pc-windows-msvc
      - run: cargo build --release --target aarch64-pc-windows-msvc
  x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
      - run: cargo build --release --target x86_64-pc-windows-msvc
